require('basic')
require('keybindings')
require('keybindings-private')
require('plugins')
require('colorscheme')
require('plugin-config.nvim-tree')
require('plugin-config.bufferline')
require('plugin-config.lualine')
require('plugin-config.dashboard')
require('plugin-config.project')
require('plugin-config.nvim-treesitter')
require('lsp.setup')
require('lsp.cmp') -- 代码补全
require('plugin-config.symbols-outline')
